const OWNER='Senna-Lin';
const REPOS={codex:'kaohsiung-land-archive-codex-windows',antigravity:'kaohsiung-land-archive-platform-ai-studio_Antigravity'};
const MANIFEST='governance/dashboard-evidence.json';
const WEIGHTS={featureCoverage:25,backendImplementation:20,dataAccess:15,automatedTests:15,ciCd:10,governanceEvidence:15};
const LABELS={featureCoverage:'功能覆蓋',backendImplementation:'後端實作',dataAccess:'資料存取',automatedTests:'自動化測試',ciCd:'CI／CD',governanceEvidence:'治理與證據'};
function dayCount(){const end=new Date('2026-10-15T23:59:59+08:00');document.querySelector('#days').textContent=Math.max(0,Math.ceil((end-new Date())/86400000))+' 天'}
async function api(path,t){const r=await fetch('https://api.github.com'+path,{headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+t,'X-GitHub-Api-Version':'2022-11-28'}});if(!r.ok)throw new Error(r.status+' '+r.statusText);return r.json()}
function decodeBase64(s){const b=atob((s||'').replace(/\n/g,''));const bytes=Uint8Array.from(b,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
async function evidenceFreshness(base,manifest,head,t){if(!manifest)return{fresh:false,reason:'missing'};if(manifest.sourceHeadSha===head)return{fresh:true,reason:'exact-head'};try{const cmp=await api(base+'/compare/'+manifest.sourceHeadSha+'...'+head,t);const files=cmp.files||[];const manifestOnly=files.length>0&&files.every(f=>f.filename===MANIFEST);return{fresh:manifestOnly,reason:manifestOnly?'manifest-only-delta':'repository-changed'}}catch(e){return{fresh:false,reason:'compare-failed'}}}
async function loadLine(key,t){const repo=REPOS[key],base='/repos/'+OWNER+'/'+repo;const [commit,prs,runs,commits]=await Promise.all([api(base+'/commits/main',t),api(base+'/pulls?state=open&per_page=20',t),api(base+'/actions/runs?per_page=5',t),api(base+'/commits?per_page=5',t)]);let manifest=null,manifestError=null;try{const f=await api(base+'/contents/'+MANIFEST+'?ref=main',t);manifest=JSON.parse(decodeBase64(f.content))}catch(e){manifestError=e.message}const head=commit.sha;const freshness=await evidenceFreshness(base,manifest,head,t);const fresh=freshness.fresh;const calibrated=fresh&&manifest?.calibrationStatus==='calibrated'&&Object.keys(WEIGHTS).every(k=>typeof manifest.metrics?.[k]==='number');return{key,repo,head,prs,runs:runs.workflow_runs||[],commits,manifest,manifestError,fresh,freshnessReason:freshness.reason,calibrated}}
function weightedScore(line){if(!line.calibrated)return null;return Math.round(Object.entries(WEIGHTS).reduce((s,[k,w])=>s+line.manifest.metrics[k]*w/100,0))}
function evidenceState(line){if(!line.manifest)return['MISSING','bad'];if(!line.fresh)return['STALE','bad'];if(line.manifest.calibrationStatus!=='calibrated')return['NEEDS CALIBRATION','warn'];return['FRESH','ok']}
function fmt(v){return typeof v==='number'?Math.round(v)+'%':'—'}
function renderLines(lines){const el=document.querySelector('#lineStatus');el.innerHTML=lines.map(l=>{const [state,cls]=evidenceState(l),run=l.runs[0],score=weightedScore(l);return `<div class="status"><span><b>${l.key==='codex'?'Codex Windows':'Antigravity Mac'}</b><br><small class="muted">HEAD ${l.head.slice(0,7)} · Open PR ${l.prs.length} · CI ${run?(run.conclusion||run.status):'—'} · Evidence ${l.freshnessReason||'—'}</small></span><span class="badge ${cls}">${state}${score===null?'':' · '+score}</span></div>`}).join('')}
function renderMetrics(lines){const c=lines.find(x=>x.key==='codex'),a=lines.find(x=>x.key==='antigravity');document.querySelector('#metricBody').innerHTML=Object.entries(WEIGHTS).map(([k,w])=>`<tr><td>${LABELS[k]}</td><td>${w}%</td><td>${c?.calibrated?fmt(c.manifest.metrics[k]):'—'}</td><td>${a?.calibrated?fmt(a.manifest.metrics[k]):'—'}</td></tr>`).join('')}
function featureMap(line){const m=new Map();(line.manifest?.features||[]).forEach(f=>m.set(f.id||f.name,f));return m}
function renderFeatures(lines){const c=featureMap(lines.find(x=>x.key==='codex')),a=featureMap(lines.find(x=>x.key==='antigravity'));const ids=[...new Set([...c.keys(),...a.keys()])];document.querySelector('#featureBody').innerHTML=ids.length?ids.map(id=>{const cf=c.get(id),af=a.get(id),name=cf?.name||af?.name||id;return `<tr><td><b>${name}</b></td><td>${fmt(cf?.progress)}<br><span class="muted">${cf?.status||'—'}</span></td><td>${fmt(af?.progress)}<br><span class="muted">${af?.status||'—'}</span></td><td>${(cf?.evidence?.length||0)+(af?.evidence?.length||0)} evidence refs</td></tr>`}).join(''):'<tr><td colspan="4" class="muted">尚未完成 feature-level calibration；v6 不會使用舊快照填補數字。</td></tr>'}
function renderRisks(lines){const risks=lines.flatMap(l=>(l.manifest?.risks||[]).map(r=>({...r,line:l.key})));document.querySelector('#riskCount').textContent=risks.filter(r=>String(r.severity).toLowerCase()==='high').length;document.querySelector('#risks').innerHTML=risks.length?risks.map(r=>`<div class="status"><span><b>${r.line==='codex'?'Codex':'Antigravity'} · ${r.title||r.id}</b><br><small class="muted">${r.detail||''}</small></span><span class="badge ${String(r.severity).toLowerCase()==='high'?'bad':'warn'}">${r.severity||'risk'}</span></div>`).join(''):'<div class="muted">沒有 manifest risk evidence。</div>'}
function renderGates(lines){document.querySelector('#nextGates').innerHTML=lines.map(l=>`<div class="status"><span>${l.key==='codex'?'Codex':'Antigravity'}</span><b>${l.manifest?.nextGate||'建立／校準 dashboard evidence manifest'}</b></div>`).join('')}
function renderActivity(lines){const xs=[];lines.forEach(l=>(l.commits||[]).slice(0,4).forEach(c=>xs.push({d:new Date(c.commit.author.date),t:`${l.key==='codex'?'Codex':'Antigravity'}: ${c.commit.message.split('\n')[0]}`})));xs.sort((a,b)=>b.d-a.d);document.querySelector('#activity').innerHTML=xs.slice(0,8).map(x=>`<div class="row"><span>${x.t}</span><small class="muted">${x.d.toLocaleString('zh-TW')}</small></div>`).join('')}
function renderKpis(lines){const c=lines.find(x=>x.key==='codex'),a=lines.find(x=>x.key==='antigravity'),cs=weightedScore(c),as=weightedScore(a);document.querySelector('#codexScore').textContent=cs??'—';document.querySelector('#antScore').textContent=as??'—';document.querySelector('#codexEvidence').textContent=evidenceState(c)[0];document.querySelector('#antEvidence').textContent=evidenceState(a)[0];const fc=[c,a].filter(x=>x.calibrated).map(x=>x.manifest.metrics.featureCoverage);document.querySelector('#common').textContent=fc.length===2?Math.round((fc[0]+fc[1])/2)+'%':'—'}
async function connect(){const t=sessionStorage.getItem('v6GithubToken');if(!t){document.querySelector('#modal').classList.add('show');return}try{document.querySelector('#connect').textContent='連線中…';const lines=await Promise.all([loadLine('codex',t),loadLine('antigravity',t)]);renderKpis(lines);renderLines(lines);renderMetrics(lines);renderFeatures(lines);renderRisks(lines);renderGates(lines);renderActivity(lines);document.querySelector('#connect').textContent='已連線 GitHub'}catch(e){document.querySelector('#connect').textContent='連線失敗';alert('GitHub 連線失敗：'+e.message)}}
document.querySelector('#connect').onclick=connect;document.querySelector('#refresh').onclick=()=>sessionStorage.getItem('v6GithubToken')?connect():location.reload();document.querySelector('#cancel').onclick=()=>document.querySelector('#modal').classList.remove('show');document.querySelector('#save').onclick=()=>{const t=document.querySelector('#token').value.trim();if(!t)return;sessionStorage.setItem('v6GithubToken',t);document.querySelector('#token').value='';document.querySelector('#modal').classList.remove('show');connect()};dayCount();if(sessionStorage.getItem('v6GithubToken'))connect();
